<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-DO7M1Q3" failures="1" tests="5" name="Default test" time="86.369" errors="0" timestamp="2022-03-01T14:06:10 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="29.945"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="18.587"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="11.2"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="12.105">
    <failure type="java.lang.AssertionError" message="expected [validation failed1] but found [validation failed]">
      <![CDATA[java.lang.AssertionError: expected [validation failed1] but found [validation failed]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at stepsDefinitions.LoginSteps.i_should_get_validation_alert_with(LoginSteps.java:61)
at âœ½.I should get validation alert with  "validation failed1"(classpath:features/login.feature:11)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="10.259"/>
</testsuite> <!-- Default test -->
